export const routes = {
  home: '/',
  marketplace: '/marketplace',
  dashboard: '/dashboard',
  education: '/education',
  contact: '/contact',
  login: '/login',
  register: '/register',
  portal: '/portal',
  category: '/category',
  penjual: '/penjual',
  news: '/news',
  faq: '/faq',
  checkout: '/checkout',
  orderTracking: '/orders/:orderId',
  faq: '/faq',
};
